import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import CartProvider from "./components/CartProvider";
import ShoppingCartModal from "./components/ShoppingCartModel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className &&
          "bg-gradient-to-r slide-in-from-top-0 from-purple-400 to-red-400"
        }
      >
        <CartProvider>
          <Navbar />
          <ShoppingCartModal />
          <div className="">{children}</div>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
